#!/bin/bash
echo ""
echo "========================="
echo "====  flatpak update ===="
echo "========================="
/usr/bin/flatpak update -y

echo "========================="
echo "======  gupdate   ======"
echo "========================="

declare -a folders=()

# Loop through the folders in the /home/lwh folder
for dir in /home/lwh/git/*; do

  # Check if the folder name contains "zzz_"
  if [[ $dir =~ zzz_ ]]; then

    # Add the folder name to the folders array
    folders+=($dir)
  fi
done

RED='\033[1;33m'
GREEN='\033[1;32m'
NC='\033[0m' # No Color

# Loop through the folders
for folder in "${folders[@]}"
do
	printf "${RED}GIT refresh${NC} : ${GREEN}$folder${NC}\n"
	cd $folder
	git reset --hard HEAD
	git pull
	echo ""
done

cp -f /home/lwh/git/zzz_ani-cli/ani-cli /home/lwh/.local/bin/ani-cli
cp -f /home/lwh/git/zzz_dra-cla/dra-cla /home/lwh/.local/bin/dra-cla
cp -f /home/lwh/git/zzz_jerry/jerry.sh /home/lwh/.local/bin/jerry
cp -f /home/lwh/git/zzz_lobster/lobster.sh /home/lwh/.local/bin/lobster

