#!/usr/bin/env bash

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
# shellcheck source=/dev/null
source "${SCRIPT_DIR/%scripts\/*/scripts}/_common_functions"

# Initial checks
_check_dependencies zip || exit 1
INPUT_FILES=$(_get_files "$*" "a" "1" "" "") || exit 1

nemo $INPUT_FILES
