[FileDialog]
history=@Invalid()
lastVisited=file:///media/lwh/lwh_backup/Games
qtVersion=6.11.1
shortcuts=file:///home/lwh/Desktop, file:///home/lwh/Documents, file:///home/lwh, file:///home/lwh/Music, file:///home/lwh/Pictures, file:///home/lwh/Videos, file:///home/lwh/Downloads
sidebarWidth=205
treeViewHeader=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1\xec\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\0\xff\0\0\0\x1\0\0\0\0\0\0\0?\0\0\0\x1\0\0\0\0\0\0\0@\0\0\0\x1\0\0\0\0\0\0\0n\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff\0\0\0\0)
viewMode=List
