# Subscription configuration file for CUPS v2.4.10
# Written by cupsd
NextSubscriptionId 1334
<Subscription 1332>
Events printer-changed
Owner root
LeaseDuration 86400
Interval 60
ExpirationTime 1791167232
NextEventId 1
</Subscription>
<Subscription 1333>
Events all
Owner anonymous
Recipient dbus://
LeaseDuration 86400
Interval 0
ExpirationTime 1791167232
NextEventId 1
</Subscription>
