# Subscription configuration file for CUPS v2.4.10
# Written by cupsd
NextSubscriptionId 1332
<Subscription 1330>
Events printer-changed
Owner root
LeaseDuration 86400
Interval 60
ExpirationTime 1791163575
NextEventId 1
</Subscription>
<Subscription 1331>
Events all
Owner anonymous
Recipient dbus://
LeaseDuration 86400
Interval 0
ExpirationTime 1791163575
NextEventId 1
</Subscription>
